# Generated by Django 5.0.6 on 2024-05-29 02:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("WEB", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empleado",
            name="email_empleado",
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
